#pragma once

#include "Acrylic/Runtime/ApplicationCore/Application.h"
#include "Acrylic/Runtime/Core/Containers/Array.h"
#include "Acrylic/Runtime/Core/Containers/Pair.h"
#include "Acrylic/Runtime/Core/Containers/String.h"
#include "Acrylic/Runtime/Core/Logging.h"
#include "Acrylic/Runtime/Core/Core.h"
#include "Acrylic/Runtime/Core/Timestep.h"
#include "Acrylic/Runtime/Events/ApplicationEvent.h"
#include "Acrylic/Runtime/Events/KeyEvent.h"
#include "Acrylic/Runtime/Events/MouseEvent.h"
#include "Acrylic/Runtime/Layers/Layer.h"
#include "Acrylic/Runtime/Layers/LayerStack.h"
#include "Acrylic/Runtime/Layers/ImGui/ImGuiLayer.h"
#include "Acrylic/Runtime/Input/Input.h"
#include "Acrylic/Runtime/Input/KeyCodes.h"
#include "Acrylic/Runtime/Input/MouseButtonCodes.h"

#include "Acrylic/Runtime/Renderer/Buffer.h"
#include "Acrylic/Runtime/Renderer/CommandList.h"
#include "Acrylic/Runtime/Renderer/Context.h"
#include "Acrylic/Runtime/Renderer/Renderer.h"
#include "Acrylic/Runtime/Renderer/Renderer2D.h"
#include "Acrylic/Runtime/Renderer/RHI.h"
#include "Acrylic/Runtime/Renderer/Shader.h"
#include "Acrylic/Runtime/Renderer/Texture.h"
#include "Acrylic/Runtime/Renderer/VertexArray.h"

#include "Acrylic/Runtime/Camera/Camera.h"
#include "Acrylic/Runtime/Camera/OrthographicCamera/OrthographicCamera.h"
#include "Acrylic/Runtime/Camera/OrthographicCamera/OrthographicCameraController.h"
